### ISSUE TITLE
Weight unit in Kg

### ISSUE THREAD

**Issue by jedeweb** [Forza-Open-Tools/Base-Tune-Calculator#1]
### Description

Using 'Kg' as the unit for weight in the GUI interface causes the application to crash with message `can't multiply sequence by non-int of type 'float'`.

### How to reproduce

- start the GUI application by running main.py
- select 'Kg' for Weight Unit
- set a Weight (1000 for instance)
- click 'Tune Car' button

### Proposed fix

The problem seems to come from https://github.com/OPTN-Club/Base-Tune-Calculator/blob/main/main.py#L11 where a text value is stored in `WeightValue` whereas a float value is expected by future users of the variable. Converting value returned by `ui.lineWeight.text()` to float should fix the problem.

**Comment by Ldalvik** [comment]
PR submitted and merged. Closing.
